name: Build Linux AMD64 Binary Go1.23

on:
  workflow_dispatch: # 支持手动触发工作流

jobs:
  build:
    name: Build for Linux AMD64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set up Go Environment
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Build Binary
      run: |
        mkdir -p build
        GOOS=linux GOARCH=amd64 go build -o build/hproxy hproxy.go

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: alist-proxy-linux-amd64
        path: build/hproxy
